language: node_js
node_js:
  - "6"
install:
  - npm install
  - npm install gulp vinyl-ftp minimist gulp-images-resizer fancy-log --save-dev
script:
  - gulp
after_success:
  - find css -type f -exec ./upload.sh {} \;
  - find img -type f -exec ./upload.sh {} \;
  - find js -type f -exec ./upload.sh {} \;
  - find thumb -type f -exec ./upload.sh {} \;
  - find vendor -type f -exec ./upload.sh {} \;
  - find . -name '*.html' -exec ./upload.sh {} \;
  - find . -name '*.ico' -exec ./upload.sh {} \;