name: Github pages deploy
on:
  push:
    branches-ignore:
      - gh-pages
  pull_request:
    branches:
      - master
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - uses: actions/setup-node@v1
        with:
          node-version: '12'
      - run: npm install
      - run: npm run build
      - run: rm .gitignore
      - run: rm -rf node_modules
      - run: git branch -m master gh-pages
      - name: Deploy
        if: success() && github.ref == 'refs/heads/master'
        uses: crazy-max/ghaction-github-pages@v2
        with:
          target_branch: gh-pages
          build_dir: .
        env:
          GH_PAT: ${{ secrets.GITHUBPAT }}
